from rest_framework import serializers
from django.contrib.auth.models import User
from patients.models import Patient, VitalSigns, LabResult, Imaging, NIHSSScore
from neurologists.models import Neurologist, Consultation, TreatmentOrder, TestOrder
from alerts.models import Alert, AlertRule, AlertLog
from .models import APIKey, APIUsageLog, APIRateLimit

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email']

class VitalSignsSerializer(serializers.ModelSerializer):
    class Meta:
        model = VitalSigns
        fields = '__all__'

class LabResultSerializer(serializers.ModelSerializer):
    class Meta:
        model = LabResult
        fields = '__all__'

class ImagingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Imaging
        fields = '__all__'

class NIHSSScoreSerializer(serializers.ModelSerializer):
    class Meta:
        model = NIHSSScore
        fields = '__all__'

class PatientSerializer(serializers.ModelSerializer):
    vital_signs = VitalSignsSerializer(many=True, read_only=True)
    lab_results = LabResultSerializer(many=True, read_only=True)
    imaging_studies = ImagingSerializer(many=True, read_only=True)
    nihss_scores = NIHSSScoreSerializer(many=True, read_only=True)

    class Meta:
        model = Patient
        fields = ['id', 'name', 'age', 'sex', 'chief_complaint', 'medical_history',
                 'created_at', 'updated_at', 'vital_signs', 'lab_results',
                 'imaging_studies', 'nihss_scores']

class TreatmentOrderSerializer(serializers.ModelSerializer):
    class Meta:
        model = TreatmentOrder
        fields = '__all__'

class TestOrderSerializer(serializers.ModelSerializer):
    class Meta:
        model = TestOrder
        fields = '__all__'

class NeurologistSerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)
    
    class Meta:
        model = Neurologist
        fields = ['id', 'user', 'license_number', 'phone_number',
                 'hospital_affiliation', 'is_available', 'created_at', 'updated_at']

class ConsultationSerializer(serializers.ModelSerializer):
    patient = PatientSerializer(read_only=True)
    neurologist = NeurologistSerializer(read_only=True)
    treatment_orders = TreatmentOrderSerializer(many=True, read_only=True)
    test_orders = TestOrderSerializer(many=True, read_only=True)

    class Meta:
        model = Consultation
        fields = ['id', 'patient', 'neurologist', 'status', 'diagnosis',
                 'recommendations', 'created_at', 'updated_at', 'completed_at',
                 'treatment_orders', 'test_orders']

class AlertRuleSerializer(serializers.ModelSerializer):
    class Meta:
        model = AlertRule
        fields = '__all__'

class AlertLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = AlertLog
        fields = '__all__'

class AlertSerializer(serializers.ModelSerializer):
    created_by = UserSerializer(read_only=True)
    recipients = UserSerializer(many=True, read_only=True)
    notification_logs = AlertLogSerializer(many=True, read_only=True)

    class Meta:
        model = Alert
        fields = ['id', 'title', 'message', 'priority', 'status', 'created_by',
                 'recipients', 'content_type', 'object_id', 'created_at',
                 'updated_at', 'acknowledged_at', 'resolved_at', 'notification_logs']

class APIKeySerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)

    class Meta:
        model = APIKey
        fields = ['id', 'user', 'key', 'name', 'is_active', 'created_at',
                 'expires_at', 'last_used_at']
        read_only_fields = ['key']  # The key should be generated by the system

class APIUsageLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = APIUsageLog
        fields = '__all__'

class APIRateLimitSerializer(serializers.ModelSerializer):
    class Meta:
        model = APIRateLimit
        fields = '__all__' 